<?php
/*
 * Chronolabs XOOPS Chat Module - xALKY
 * 
 * You may not change or alter any portion of this comment or credits
 * of supporting developers from this source code or any supporting source code
 * which is considered copyrighted (c) material of the original comment or credit authors.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 
 * @copyright 		Chronolabs Cooperative http://labs.coop
 * @license 		General Software Licence (https://web.labs.coop/public/legal/general-software-license/10,3.html)
 * @package 		xalky
 * @since 			1.111
 * @author 			Antony Cipher <cipher@labs.coop>
 * @author 			Simon Roberts <meshy@labs.coop>
 * @subpackage		kerne
 * @description		Chronolabs XOOPS Module for Chat and Walky Talky Services
 * 
 */
 

$modversion = array();
$modversion['name'] = _XALKY_MI_;
$modversion['version'] = _XALKY_MI_;
$modversion['description'] = _XALKY_MI_;
$modversion['author'] = _XALKY_MI_;
$modversion['credits'] = _XALKY_MI_;
$modversion['help'] = 'page=help';
$modversion['license'] = 'Chronolabs GSL';
$modversion['license_url'] = "web.labs.coop/public/legal/general-software-license/10,3.html";
$modversion['image'] = "image/xalky.png";
$modversion['dirname'] = "xalky";
$modversion['dirmoduleadmin'] = '/Frameworks/moduleclasses/moduleadmin';
$modversion['icons16'] = 'image/icons/16';
$modversion['icons32'] = 'image/icons/32';

//about
$modversion["module_status"] = "Prealpha";
$modversion['release_date'] = '2014/10/20';
$modversion["module_website_url"] = "http://labs.coop/";
$modversion["module_website_name"] = "Chronolabs Cooperative";
$modversion['min_php'] = '5.3.7';
$modversion['min_xoops'] = "2.5.7";
$modversion['min_admin'] = '1.1';
$modversion['min_db'] = array(
 'mysql' => '5.0.7',
 'mysqli' => '5.0.7'
);

// Admin menu
// Set to 1 if you want to display menu generated by system module
$modversion['system_menu'] = 1;

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/admin.php";
$modversion['adminmenu'] = "admin/menu.php";

// Mysql file
$modversion['sqlfile']['mysql'] = "sql/chat.sql";

// Table
$modversion['tables'][0] = "xalky_bans";
$modversion['tables'][1] = "xalky_invitations";
$modversion['tables'][2] = "xalky_onliner";
$modversion['tables'][3] = "xalky_messages";


// Templates
$modversion['templates'] = array();
$modversion['templates'][1]['file'] = 'xalky_loggedon.html';
$modversion['templates'][1]['description'] = 'Logged on Wrapper';
$modversion['templates'][2]['file'] = 'xalky_loggedout.html';
$modversion['templates'][2]['description'] = 'Logged out Wrapper';

// Menu
$modversion['hasMain'] = 1;
$modversion['config'][] = array(
		'name' => 'htaccess',
		'title' => '_XALKY_MI_',
		'description' => '_XALKY_MI_',
		'formtype' => '',
		'valuetype' => '',
		'default' => false
);

$modversion['config'][] = array(
		'name' => 'htaccess_path',
		'title' => '_XALKY_MI_',
		'description' => '_XALKY_MI_',
		'formtype' => '',
		'valuetype' => '',
		'default' => ''
);

$modversion['config'][] = array(
		'name' => 'htaccess_extension',
		'title' => '_XALKY_MI_',
		'description' => '_XALKY_MI_',
		'formtype' => '',
		'valuetype' => '',
		'default' => '.html'
);

$modversion['config'][] = array(
		'name' => 'defaultstyle',
		'title' => '_XALKY_MI_',
		'description' => '_XALKY_MI_',
		'formtype' => '',
		'valuetype' => '',
		'default' => false
);

$modversion['config'][] = array(
		'name' => 'defaultchannel',
		'title' => '_XALKY_MI_',
		'description' => '_XALKY_MI_',
		'formtype' => '',
		'valuetype' => '',
		'default' => false
);

$modversion['config'][] = array(
		'name' => 'privatechannels',
		'title' => '_XALKY_MI_',
		'description' => '_XALKY_MI_',
		'formtype' => '',
		'valuetype' => '',
		'default' => false
);

$modversion['config'][] = array(
		'name' => 'privatemessages',
		'title' => '_XALKY_MI_',
		'description' => '_XALKY_MI_',
		'formtype' => '',
		'valuetype' => '',
		'default' => false
);

$modversion['config'][] = array(
	 'name' => 'channelprefix',
	 'title' => '_XALKY_MI_',
	 'description' => '_XALKY_MI_',
	 'formtype' => '',
	 'valuetype' => '',
	 'default' => ''
);

$modversion['config'][] = array(
	 'name' => 'channelsuffix',
	 'title' => '_XALKY_MI_',
	 'description' => '_XALKY_MI_',
	 'formtype' => '',
	 'valuetype' => '',
	 'default' => false
);

$modversion['config'][] = array(
		'name' => 'autologin',
		'title' => '_XALKY_MI_',
		'description' => '_XALKY_MI_',
		'formtype' => '',
		'valuetype' => '',
		'default' => 'watermark.gif'
);

$modversion['config'][] = array(
		'name' => 'showmessages',
		'title' => '_XALKY_MI_',
		'description' => '_XALKY_MI_',
		'formtype' => '',
		'valuetype' => '',
		'default' => false
);

$modversion['config'][] = array(
		'name' => 'closed',
		'title' => '_XALKY_MI_',
		'description' => '_XALKY_MI_',
		'formtype' => '',
		'valuetype' => '',
		'default' => false
);

$modversion['config'][] = array(
		'name' => 'openinghour',
		'title' => '_XALKY_MI_',
		'description' => '_XALKY_MI_',
		'formtype' => '',
		'valuetype' => '',
		'default' => false
);

$modversion['config'][] = array(
		'name' => 'closinghour',
		'title' => '_XALKY_MI_',
		'description' => '_XALKY_MI_',
		'formtype' => '',
		'valuetype' => '',
		'default' => false
);

$modversion['config'][] = array(
		'name' => 'opendays',
		'title' => '_XALKY_MI_',
		'description' => '_XALKY_MI_',
		'formtype' => '',
		'valuetype' => '',
		'default' => false
);

$modversion['config'][] = array(
		'name' => 'allowguests',
		'title' => '_XALKY_MI_',
		'description' => '_XALKY_MI_',
		'formtype' => '',
		'valuetype' => '',
		'default' => false
);

$modversion['config'][] = array(
		'name' => 'allowguestswrite',
		'title' => '_XALKY_MI_',
		'description' => '_XALKY_MI_',
		'formtype' => 'select',
		'valuetype' => '',
		'options' 	 => array(), 
		'default' => false
);

$modversion['config'][] = array(
		'name' => 'allowguestusername',
		'title' => '_XALKY_MI_',
		'description' => '_XALKY_MI_',
		'formtype' => '',
		'valuetype' => '',
		'default' => false
);

$modversion['config'][] = array(
		'name' => 'guestprefix',
		'title' => '_XALKY_MI_',
		'description' => '_XALKY_MI_',
		'formtype' => 'select',
		'valuetype' => '',
		'options' 	 => array(),
		'default' => ''
);

$modversion['config'][] = array(
		'name' => 'guestsuffix',
		'title' => '_XALKY_MI_',
		'description' => '_XALKY_MI_',
		'formtype' => 'select',
		'valuetype' => '',
		'options' 	 => array(),
		'default' => ''
);

$modversion['config'][] = array(
		'name' => 'allownickchange',
		'title' => '_XALKY_MI_',
		'description' => '_XALKY_MI_',
		'formtype' => 'select',
		'valuetype' => '',
		'options' 	 => array(),
		'default' => ''
);

$modversion['config'][] = array(
		'name' => 'nickprefix',
		'title' => '_XALKY_MI_',
		'description' => '_XALKY_MI_',
		'formtype' => 'select',
		'valuetype' => '',
		'options' 	 => array(),
		'default' => ''
);

$modversion['config'][] = array(
		'name' => 'nicksuffix',
		'title' => '_XALKY_MI_',
		'description' => '_XALKY_MI_',
		'formtype' => 'select',
		'valuetype' => '',
		'options' 	 => array(),
		'default' => ''
);

$modversion['config'][] = array(
		'name' => 'usermsgdelete',
		'title' => '_XALKY_MI_',
		'description' => '_XALKY_MI_',
		'formtype' => '',
		'valuetype' => '',
		'default' => false
);

$modversion['config'][] = array(
		'name' => 'botname',
		'title' => '_XALKY_MI_',
		'description' => '_XALKY_MI_',
		'formtype' => '',
		'valuetype' => '',
		'default' => false
);

$modversion['config'][] = array(
		'name' => 'inactivetimeout',
		'title' => '_XALKY_MI_',
		'description' => '_XALKY_MI_',
		'formtype' => '',
		'valuetype' => '',
		'default' => false
);

$modversion['config'][] = array(
		'name' => 'inactiveerval',
		'title' => '_XALKY_MI_',
		'description' => '_XALKY_MI_',
		'formtype' => '',
		'valuetype' => '',
		'default' => false
);

$modversion['config'][] = array(
		'name' => 'priorchannel',
		'title' => '_XALKY_MI_',
		'description' => '_XALKY_MI_',
		'formtype' => '',
		'valuetype' => '',
		'default' => ''
); 

$modversion['config'][] = array(
		'name' => 'priorchannellist',
		'title' => '_XALKY_MI_',
		'description' => '_XALKY_MI_',
		'formtype' => 'select',
		'valuetype' => '',
		'options' 	 => array(),
		'default' => ''
);

$modversion['config'][] = array(
		'name' => 'timediff',
		'title' => '_XALKY_MI_',
		'description' => '_XALKY_MI_',
		'formtype' => '',
		'valuetype' => '',
		'default' => false
);

$modversion['config'][] = array(
		'name' => 'limit',
		'title' => '_XALKY_MI_',
		'description' => '_XALKY_MI_',
		'formtype' => '',
		'valuetype' => '',
		'default' => false
);


$modversion['config'][] = array(
		'name' => 'maxusers',
		'title' => '_XALKY_MI_',
		'description' => '_XALKY_MI_',
		'formtype' => '',
		'valuetype' => '',
		'default' => false
);

$modversion['config'][] = array(
		'name' => 'namemaxlength',
		'title' => '_XALKY_MI_',
		'description' => '_XALKY_MI_',
		'formtype' => '',
		'valuetype' => '',
		'default' => false
);


$modversion['config'][] = array(
		'name' => 'maxchars',
		'title' => '_XALKY_MI_',
		'description' => '_XALKY_MI_',
		'formtype' => '',
		'valuetype' => '',
		'default' => false
);

$modversion['config'][] = array(
		'name' => 'msgrate',
		'title' => '_XALKY_MI_',
		'description' => '_XALKY_MI_',
		'formtype' => '',
		'valuetype' => '',
		'default' => false
);

$modversion['config'][] = array(
		'name' => 'bantime',
		'title' => '_XALKY_MI_',
		'description' => '_XALKY_MI_',
		'formtype' => '',
		'valuetype' => '',
		'default' => false
);

$modversion['config'][] = array(
		'name' => 'logoutpath',
		'title' => '_XALKY_MI_',
		'description' => '_XALKY_MI_',
		'formtype' => '',
		'valuetype' => '',
		'default' => false
);

$modversion['config'][] = array(
		'name' => 'ipcheck',
		'title' => '_XALKY_MI_',
		'description' => '_XALKY_MI_',
		'formtype' => '',
		'valuetype' => '',
		'default' => false
);

?>