<?php
/**
 * Xalky - Talks like a cockatoo - XOOPS Chat Rooms
 *
 * You may not change or alter any portion of this comment or credits
 * of supporting developers from this source code or any supporting source code
 * which is considered copyrighted (c) material of the original comment or credit authors.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * @copyright   Chronolabs Cooperative http://sourceforge.net/projects/chronolabs/
 * @license     GNU GPL 3 (http://labs.coop/briefs/legal/general-public-licence/13,3.html)
 * @author      Simon Antony Roberts <wishcraft@users.sourceforge.net>
 * @see			http://sourceforge.net/projects/xoops/
 * @see			http://sourceforge.net/projects/chronolabs/
 * @see			http://sourceforge.net/projects/chronolabsapi/
 * @see			http://labs.coop
 * @version     1.0.5
 * @since		1.0.1
 */



$modversion                   = array();
$modversion['name']           = _MI_XALKY_NAME;
$modversion['version']        = 1.02;
$modversion['description']    = _MI_XALKY_DESC;
$modversion['author']         = "Simon Antony Roberts";
$modversion['credits']        = "Chronolabs";
$modversion['help']           = 'page=help';
$modversion['license']        = 'GNU GPL 3.0 or later';
$modversion['license_url']    = "labs.coop/briefs/legal/general-public-licence/13,3.html";
$modversion['image']          = "assets/images/logo.png";
$modversion['dirname']        = basename(__DIR__);
$modversion['dirmoduleadmin'] = '/Frameworks/moduleclasses/moduleadmin';
$modversion['icons16']        = '../../Frameworks/moduleclasses/icons/16';
$modversion['icons32']        = '../../Frameworks/moduleclasses/icons/32';

//about
$modversion["module_status"]       = "Beta";
$modversion['release_date']        = '2015/12/08';
$modversion["module_website_url"]  = "http://labs.coop/";
$modversion["module_website_name"] = "Chronolabs";
$modversion['min_php']             = '5.3.7';
$modversion['min_xoops']           = "2.5.7";
$modversion['min_admin']           = '1.1';
$modversion['min_db']              = array(
    										'mysql'  => '5.0.7',
    										'mysqli' => '5.0.7'
									 );

$modversion['hasMain']   = 1;

// Admin menu
// Set to 1 if you want to display menu generated by system module
$modversion['system_menu'] = 1;

// Admin things
$modversion['hasAdmin']   = 1;
$modversion['adminindex'] = "admin/admin.php";
$modversion['adminmenu']  = "admin/menu.php";

// Mysql file
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";

// Table
$modversion['tables'][]	=	'xalky_blowfishing';
$modversion['tables'][]	=	'xalky_callbacks';
$modversion['tables'][]	=	'xalky_message';
$modversion['tables'][]	=	'xalky_networking';
$modversion['tables'][]	=	'xalky_peering';
$modversion['tables'][]	=	'xalky_peers';
$modversion['tables'][]	=	'xalky_profiles';
$modversion['tables'][]	=	'xalky_rooms';
$modversion['tables'][]	=	'xalky_rooms_users';
$modversion['tables'][]	=	'xalky_users';
$modversion['tables'][]	=	'xalky_whois';

// Scripts to run upon installation or update
$modversion['onInstall'] = "include/install.php";
//$modversion['onUpdate']  = "include/update.php";

// Templates
$modversion['templates']                   = array();
$modversion['templates'][1]['file']        = 'xalky_index.html';
$modversion['templates'][1]['description'] = 'Main Index for XALKY';

$modversion['config'][] = array(
		'name'        => 'chatroomName',
		'title'       => '_MI_XALKY_CHATROOMS_NAME',
		'description' => '_MI_XALKY_CHATROOMS_NAME_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'text',
		'default'     => 'Xalky :: ' . $GLOBALS['xoopsConfig']['sitename']
);

$modversion['config'][] = array(
		'name'        => 'chatroomEmail',
		'title'       => '_MI_XALKY_CHATROOM_EMAIL',
		'description' => '_MI_XALKY_CHATROOM_EMAIL_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'text',
		'default'     => $GLOBALS['xoopsConfig']['admin_email']
);

$modversion['config'][] = array(
		'name'        => 'chatroomUrl',
		'title'       => '_MI_XALKY_CHATROOM_URL',
		'description' => '_MI_XALKY_CHATROOM_URL_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'text',
		'default'     => XOOPS_URL . '/modules/xalky/'
);

$modversion['config'][] = array(
		'name'        => 'IPInfoDBapiKey',
		'title'       => '_MI_XALKY_IPINFODB_APIKEY',
		'description' => '_MI_XALKY_IPINFODB_APIKEY_DESC',
		'formtype'    => 'password',
		'valuetype'   => 'text',
		'default'     => '9bbaa1f-----------b0a8ed0820a-------------------------9ab'
);

$modversion['config'][] = array(
		'name'        => 'digitalCredits',
		'title'       => '_MI_XALKY_DIGITAL_CREDITS',
		'description' => '_MI_XALKY_DIGITAL_CREDITS_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'int',
		'default'     => '500'
);

$modversion['config'][] = array(
		'name'        => 'integrated',
		'title'       => '_MI_XALKY_INTERGRATED',
		'description' => '_MI_XALKY_INTERGRATED_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => '0'
);

$modversion['config'][] = array(
		'name'        => 'showTimeStamp',
		'title'       => '_MI_XALKY_SHOW_TIMESTAMP',
		'description' => '_MI_XALKY_SHOW_TIMESTAMP_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => '0'
);

$modversion['config'][] = array(
		'name'        => 'admin',
		'title'       => '_MI_XALKY_ADMIN',
		'description' => '_MI_XALKY_ADMIN_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => '0'
);

$modversion['config'][] = array(
		'name'        => 'showMessages',
		'title'       => '_MI_XALKY_SHOW_MESSAGES',
		'description' => '_MI_XALKY_SHOW_MESSAGES_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => '1'
);

$modversion['config'][] = array(
		'name'        => 'totalMessages',
		'title'       => '_MI_XALKY_TOTAL_MESSAGES',
		'description' => '_MI_XALKY_TOTAL_MESSAGES_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'int',
		'default'     => '30'
);

$modversion['config'][] = array(
		'name'        => 'displayMDiv',
		'title'       => '_MI_XALKY_DISPLAY_MDIV',
		'description' => '_MI_XALKY_DISPLAY_MDIV_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'text',
		'default'     => 'chatContainer'
);

$modversion['config'][] = array(
		'name'        => 'newPm',
		'title'       => '_MI_XALKY_NEW_PM',
		'description' => '_MI_XALKY_NEW_PM_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'text',
		'default'     => '#c8c8c8'
);

$modversion['config'][] = array(
		'name'        => 'newPmMin',
		'title'       => '_MI_XALKY_NEW_PM_MINIMAL',
		'description' => '_MI_XALKY_NEW_PM_MINIMAL_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'text',
		'default'     => '#c8c8c8'
);

$modversion['config'][] = array(
		'name'        => 'refreshRate',
		'title'       => '_MI_XALKY_REFRESH_RATE',
		'description' => '_MI_XALKY_REFRESH_RATE_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'int',
		'default'     => '3000'
);

$options = array();
foreach(XoopsLists::getFileListAsArray(__DIR__ . DIRECTORY_SEPARATOR . "assets" . DIRECTORY_SEPARATOR . "sounds") as $key => $file)
	if (strpos($file, ".mp3"))
		$options[basename($file)] = basename($file);
$modversion['config'][] = array(
		'name'        => 'defaultSFX',
		'title'       => '_MI_XALKY_DEFAULT_SFX',
		'description' => '_MI_XALKY_DEFAULT_SFX_DESC',
		'formtype'    => 'select',
		'valuetype'   => 'text',
		'default'     => 'beep_high.mp3',
		'options'	  => $options
);

$modversion['config'][] = array(
		'name'        => 'floodChat',
		'title'       => '_MI_XALKY_FLOODING',
		'description' => '_MI_XALKY_FLOODING_DESC',
		'formtype'    => 'select',
		'valuetype'   => 'int',
		'default'     => '2',
		'options'	  => array("Flooding Protection Broad" => 2, "Basic Flooding" => 1, "Off" => 0)
);

$modversion['config'][] = array(
		'name'        => 'enableShoutFilter',
		'title'       => '_MI_XALKY_SHOUT_FILTER',
		'description' => '_MI_XALKY_SHOUT_FILTER_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => '0'
);

$modversion['config'][] = array(
		'name'        => 'enableEmail',
		'title'       => '_MI_XALKY_EMAIL',
		'description' => '_MI_XALKY_EMAIL_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => '1'
);

$modversion['config'][] = array(
		'name'        => 'enableUrl',
		'title'       => '_MI_XALKY_URL',
		'description' => '_MI_XALKY_URL_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => '1'
);

$modversion['config'][] = array(
		'name'        => 'advertsOn',
		'title'       => '_MI_XALKY_ADVERTS',
		'description' => '_MI_XALKY_ADVERTS_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => '0'
);

$modversion['config'][] = array(
		'name'        => 'privateOn',
		'title'       => '_MI_XALKY_PRIVATE',
		'description' => '_MI_XALKY_PRIVATE_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => '1'
);

$modversion['config'][] = array(
		'name'        => 'whisperOn',
		'title'       => '_MI_XALKY_WHISPER',
		'description' => '_MI_XALKY_WHISPER_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => '1'
);

$modversion['config'][] = array(
		'name'        => 'webcamsOn',
		'title'       => '_MI_XALKY_WEBCAMS',
		'description' => '_MI_XALKY_WEBCAMS_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => '0'
);

$modversion['config'][] = array(
		'name'        => 'profileRef',
		'title'       => '_MI_XALKY_PROFILES_REF',
		'description' => '_MI_XALKY_PROFILES_REF_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => '0'
);

$modversion['config'][] = array(
		'name'        => 'profileOn',
		'title'       => '_MI_XALKY_PROFILES_ON',
		'description' => '_MI_XALKY_PROFILES_ON_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => '1'
);

$modversion['config'][] = array(
		'name'        => 'profileUrl',
		'title'       => '_MI_XALKY_PROFILES_URI',
		'description' => '_MI_XALKY_PROFILES_URI_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'text',
		'default'     => 'profiles/?id='
);

$options = array();
foreach(XoopsLists::getFileListAsArray(__DIR__ . DIRECTORY_SEPARATOR . "assets" . DIRECTORY_SEPARATOR . "sounds". DIRECTORY_SEPARATOR . "sfx") as $key => $file)
	if (strpos($file, ".mp3"))
 		$options[basename($file)] = basename($file);
$modversion['config'][] = array(
 		'name'        => 'sfx',
 		'title'       => '_MI_XALKY_SOUNDFX',
 		'description' => '_MI_XALKY_SOUNDFX_DESC',
 		'formtype'    => 'select_multi',
 		'valuetype'   => 'array',
 		'default'     => $options,
 		'options'	  => $options
 );

$modversion['config'][] = array(
		'name'        => 'font_colour',
		'title'       => '_MI_XALKY_FONT_COLOUR',
		'description' => '_MI_XALKY_FONT_COLOUR_DESC',
		'formtype'    => 'textarea',
		'valuetype'   => 'text',
		'default'     => '#000000,#003300,#006600,#009900,#00CC00,#00FF00,#000033,#003333,#006633,#009933,#00CC33,#00FF33,#000066,#003366,#006666,#009966,#00CC66,#00FF66,#000099,#003399,#006699,#009999,#00CC99,#00FF99,#0000CC,#0033CC,#0066CC,#0099CC,#00CCCC,#00FFCC,#0000FF,#0033FF,#0066FF,#0099FF,#00CCFF,#00FFFF,#990000,#993300,#996600,#999900,#99CC00,#99FF00,#990033,#993333,#996633,#999933,#99CC33,#99FF33,#990066,#993366,#996666,#999966,#99CC66,#99FF66,#990099,#993399,#996699,#999999,#99CC99,#99FF99,#9900CC,#9933CC,#9966CC,#9999CC,#99CCCC,#99FFCC,#9900FF,#9933FF,#9966FF,#9999FF,#99CCFF,#99FFFF,#FF0000,#FF3300,#FF6600,#FF9900,#FFCC00,#FFFF00,#FF0033,#FF3333,#FF6633,#FF9933,#FFCC33,#FFFF33,#FF0066,#FF3366,#FF6666,#FF9966,#FFCC66,#FFFF66,#FF0099,#FF3399,#FF6699,#FF9999,#FFCC99,#FFFF99,#FF00CC,#FF33CC,#FF66CC,#FF99CC,#FFCCCC,#FFFFCC,#FF00FF,#FF33FF,#FF66FF,#FF99FF,#FFCCFF,#FFFFFF'
);

$modversion['config'][] = array(
		'name'        => 'font_size',
		'title'       => '_MI_XALKY_FONT_SIZE',
		'description' => '_MI_XALKY_FONT_SIZE_DESC',
		'formtype'    => 'textarea',
		'valuetype'   => 'text',
		'default'     => '12px,14px,16px,18px,20px,22px'
);

$modversion['config'][] = array(
		'name'        => 'font_family',
		'title'       => '_MI_XALKY_FONT_SIZE',
		'description' => '_MI_XALKY_FONT_SIZE_DESC',
		'formtype'    => 'textarea',
		'valuetype'   => 'text',
		'default'     => 'Arial,Verdana,Times New Roman,Courier,Comic Sans MS,Georgia'
);

$modversion['config'][] = array(
		'name'        => 'badwords',
		'title'       => '_MI_XALKY_BADWORDS',
		'description' => '_MI_XALKY_BADWORDS_DESC',
		'formtype'    => 'textarea',
		'valuetype'   => 'text',
		'default'     => 'fuck,shit,cunt,biggot,rash'
);


$modversion['config'][] = array(
		'name'        => 'smilies_text',
		'title'       => '_MI_XALKY_SMILIES_TEXT',
		'description' => '_MI_XALKY_SMILIES_TEXT_DESC',
		'formtype'    => 'textarea',
		'valuetype'   => 'text',
		'default'     => ':),;),:P,:7,;(,:(,:V,[(,[x,:h,*R,8),:d,:L,:o'
);

$modversion['config'][] = array(
		'name'        => 'smilies_images',
		'title'       => '_MI_XALKY_SMILIES_IMAGES',
		'description' => '_MI_XALKY_SMILIES_IMAGES_DESC',
		'formtype'    => 'textarea',
		'valuetype'   => 'text',
		'default'     => 'smile.gif,wink.gif,puh2.gif,blush.gif,cry.gif,sadley.gif,confused.gif,frown.gif,frusty.gif,heart.gif,rolleyes.gif,shadey.gif,biggrin.gif,loveit.gif,omg.gif'
);

$options = array();
foreach(XoopsLists::getImgListAsArray(__DIR__ . DIRECTORY_SEPARATOR . "assets" . DIRECTORY_SEPARATOR . "avatars") as $key => $value)
	$options[basename($value)] = basename($value);
$modversion['config'][] = array(
		'name'        => 'avatars',
		'title'       => '_MI_XALKY_AVATARS',
		'description' => '_MI_XALKY_AVATARS_DESC',
		'formtype'    => 'select_multi',
		'valuetype'   => 'array',
		'default'     => $options,
		'options'	  => $options
);

xoops_load("XoopsLists");
$templates = $options = array();
foreach(XoopsLists::getDirListAsArray(__DIR__ . DIRECTORY_SEPARATOR . "templates") as $key => $folder)
	if (!in_array($folder, array('admin', 'blocks')))
		$templates[basename($folder)] = basename($folder);
$keys = array_keys($templates);
$modversion['config'][] = array(
		'name'        => 'template',
		'title'       => '_MI_XALKY_TEMPLATE',
		'description' => '_MI_XALKY_TEMPLATE_DESC',
		'formtype'    => 'select',
		'valuetype'   => 'text',
		'default'     => $templates[$keys[0]],
		'options'	  => $templates
);

$modversion['config'][] = array(
		'name'        => 'loginImage',
		'title'       => '_MI_XALKY_LOGIN_IMAGE',
		'description' => '_MI_XALKY_SENTRYBOT_NAME_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'text',
		'default'     => '/assets/images/loginbg.jpg'
);

$modversion['config'][] = array(
		'name'        => 'dispLastMess',
		'title'       => '_MI_XALKY_DISPLAY_LAST_MESSAGE',
		'description' => '_MI_XALKY_DISPLAY_LAST_MESSAGE_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => '1'
);

$modversion['config'][] = array(
		'name'        => 'maxUsers',
		'title'       => '_MI_XALKY_MAXIMUM_USERS_SHOWN',
		'description' => '_MI_XALKY_MAXIMUM_USERS_SHOWN_DESC',
		'formtype'    => 'select',
		'valuetype'   => 'int',
		'default'     => '100',
		'options'	  => array(	"500 Maximum Users Shown" => 500, "450 Maximum Users Shown" => 450, "400 Maximum Users Shown" => 400,
								"350 Maximum Users Shown" => 350, "300 Maximum Users Shown" => 300, "250 Maximum Users Shown" => 250,
								"200 Maximum Users Shown" => 200, "150 Maximum Users Shown" => 150, "140 Maximum Users Shown" => 140,
								"128 Maximum Users Shown" => 128, "96 Maximum Users Shown" => 96, "64 Maximum Users Shown" => 64)
);

$modversion['config'][] = array(
		'name'        => 'usersOnline',
		'title'       => '_MI_XALKY_USERS_ONLINE',
		'description' => '_MI_XALKY_USERS_ONLINE_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => '1'
);

$modversion['config'][] = array(
		'name'        => 'guestMode',
		'title'       => '_MI_XALKY_GUEST_MODE',
		'description' => '_MI_XALKY_GUEST_MODE_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => '1'
);

$modversion['config'][] = array(
		'name'        => 'userGroup',
		'title'       => '_MI_XALKY_USERGROUP',
		'description' => '_MI_XALKY_USERGROUP_DESC',
		'formtype'    => 'groups',
		'valuetype'   => 'int',
		'default'     => XOOPS_GROUP_USERS
);

$modversion['config'][] = array(
		'name'        => 'sentryBot',
		'title'       => '_MI_XALKY_SENTRYBOT',
		'description' => '_MI_XALKY_SENTRYBOT_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => '1'
);

$modversion['config'][] = array(
		'name'        => 'sentryBotName',
		'title'       => '_MI_XALKY_SENTRYBOT_NAME',
		'description' => '_MI_XALKY_SENTRYBOT_NAME_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'text',
		'default'     => 'SentryBot (c)'
);

$options = array();
foreach(XoopsLists::getImgListAsArray(__DIR__ . DIRECTORY_SEPARATOR . "assets" . DIRECTORY_SEPARATOR . "avatars") as $key => $value)
	$options[basename($value)] = DIRECTORY_SEPARATOR . "assets" . DIRECTORY_SEPARATOR . "avatars" . DIRECTORY_SEPARATOR . basename($value);
$modversion['config'][] = array(
		'name'        => 'sentryBotAvi',
		'title'       => '_MI_XALKY_SENTRYBOT_AVATAR',
		'description' => '_MI_XALKY_SENTRYBOT_AVATAR_DESC',
		'formtype'    => 'select',
		'valuetype'   => 'text',
		'default'     => DIRECTORY_SEPARATOR . "assets" . DIRECTORY_SEPARATOR . "avatars" . DIRECTORY_SEPARATOR . 'pc.gif',
		'options'	  => $options
);

$modversion['config'][] = array(
		'name'        => 'sentryBotRoomID',
		'title'       => '_MI_XALKY_SENTRYBOT_ROOMID',
		'description' => '_MI_XALKY_SENTRYBOT_ROOMID_DESC',
		'formtype'    => 'select',
		'valuetype'   => 'text',
		'default'     => xalky_getLocalRooms(true),
		'options'	  => xalky_getLocalRooms(false)
);

$modversion['config'][] = array(
		'name'        => 'smilies',
		'title'       => '_MI_XALKY_SMILES',
		'description' => '_MI_XALKY_SMILES_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => '1'
);

$modversion['config'][] = array(
		'name'        => 'ringBell',
		'title'       => '_MI_XALKY_RING_BELL',
		'description' => '_MI_XALKY_RING_BELL_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => '1'
);

$modversion['config'][] = array(
		'name'        => 'textStyles',
		'title'       => '_MI_XALKY_TEXT_STYLE',
		'description' => '_MI_XALKY_TEXT_STYLE_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => '1'
);

$modversion['config'][] = array(
		'name'        => 'userAvatars',
		'title'       => '_MI_XALKY_USER_AVATARS',
		'description' => '_MI_XALKY_USER_AVATARS_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => '1'
);

$modversion['config'][] = array(
		'name'        => 'playSFX',
		'title'       => '_MI_XALKY_PLAY_SFX',
		'description' => '_MI_XALKY_PLAY_SFX_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => '1'
);

$modversion['config'][] = array(
		'name'        => 'clearScreen',
		'title'       => '_MI_XALKY_CLEAR_SCREEN',
		'description' => '_MI_XALKY_CLEAR_SCREEN_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => '1'
);

$modversion['config'][] = array(
		'name'        => 'chatHistory',
		'title'       => '_MI_XALKY_CHAT_HISTORY',
		'description' => '_MI_XALKY_CHAT_HISTORY_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => '1'
);

foreach(xalky_getLocalPlugins(true) as $dirname => $values)
{
	$modversion['config'][] = array(
			'name'        => $values['config']['name'],
			'title'       => sprintf(constant("_MI_XALKY_PLUGIN_TITLE"), $values['name']),
			'description' => sprintf(constant("_MI_XALKY_PLUGIN_DESC"), $values['description']),
			'formtype'    => $values['config']['formtype'],
			'valuetype'   => $values['config']['valuetype'],
			'default'     => $values['config']['default'],
			'options'     => $values['config']['options']
	);
}

$modversion['config'][] = array(
		'name'        => 'defaultRoom',
		'title'       => '_MI_XALKY_DEFAULT_ROOM',
		'description' => '_MI_XALKY_DEFAULT_ROOM_DESC',
		'formtype'    => 'select',
		'valuetype'   => 'text',
		'default'     => xalky_getLocalRooms(true),
		'options'	  => xalky_getLocalRooms(false)
);

$modversion['config'][] = array(
		'name'        => 'kickTime',
		'title'       => '_MI_XALKY_KICK_TIME',
		'description' => '_MI_XALKY_KICK_TIME_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'int',
		'default'     => '15'
);

$modversion['config'][] = array(
		'name'        => 'silent',
		'title'       => '_MI_XALKY_SILENT',
		'description' => '_MI_XALKY_SILENT_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'int',
		'default'     => '5'
);

$modversion['config'][] = array(
		'name'        => 'singleRoom',
		'title'       => '_MI_XALKY_SINGLE_ROOM',
		'description' => '_MI_XALKY_SINGLE_ROOM_DESC',
		'formtype'    => 'select',
		'valuetype'   => 'int',
		'default'     => '0',
		'options'	  => array('Multi-room\'s Support'=>0, 'Single-roomed Support'=>1)
);

$modversion['config'][] = array(
		'name'        => 'approve',
		'title'       => '_MI_XALKY_APPROVE',
		'description' => '_MI_XALKY_APPROVE_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => '0'
);

$modversion['config'][] = array(
		'name'        => 'banIP',
		'title'       => '_MI_XALKY_BAN_IP',
		'description' => '_MI_XALKY_BAN_IP_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => '0'
);

$modversion['config'][] = array(
		'name'        => 'text_bold',
		'title'       => '_MI_XALKY_TEXT_BOLD',
		'description' => '_MI_XALKY_TEXT_BOLD_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => '0'
);

$modversion['config'][] = array(
		'name'        => 'text_underline',
		'title'       => '_MI_XALKY_TEXT_UNDERLINE',
		'description' => '_MI_XALKY_TEXT_UNDERLINE_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => '0'
);


$modversion['config'][] = array(
		'name'        => 'text_italic',
		'title'       => '_MI_XALKY_TEXT_ITALIC',
		'description' => '_MI_XALKY_TEXT_ITALIC_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => '0'
);


$modversion['config'][] = array(
		'name'        => 'text_colour',
		'title'       => '_MI_XALKY_TEXT_COLOUR',
		'description' => '_MI_XALKY_TEXT_COLOUR_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'text',
		'default'     => '#011110'
);


$modversion['config'][] = array(
		'name'        => 'text_size',
		'title'       => '_MI_XALKY_TEXT_SIZE',
		'description' => '_MI_XALKY_TEXT_SIZE_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'text',
		'default'     => '1.095em'
);

$modversion['config'][] = array(
		'name'        => 'text_family',
		'title'       => '_MI_XALKY_TEXT_FAMILY',
		'description' => '_MI_XALKY_TEXT_FAMILY_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'text',
		'default'     => 'Verdana, Tahoma, Arial, San-serif, San'
);

$modversion['config'][] = array(
		'name'        => 'maxChars',
		'title'       => '_MI_XALKY_MAXIMUM_CHARS',
		'description' => '_MI_XALKY_MAXIMUM_CHARS_DESC',
		'formtype'    => 'select',
		'valuetype'   => 'int',
		'default'     => '500',
		'options'	  => array(	"500 Character Message's" => 500, "450 Character Message's" => 450, "400 Character Message's" => 400,
								"350 Character Message's" => 350, "300 Character Message's" => 300, "250 Character Message's" => 250,
								"200 Character Message's" => 200, "150 Character Message's" => 150, "140 Character Message's" => 140,
								"128 Character Message's" => 128, "96 Character Message's" => 96, "64 Character Message's" => 64)
);

$modversion['config'][] = array(
		'name'        => 'idleTimeout',
		'title'       => '_MI_XALKY_IDLE_TIMEOUT',
		'description' => '_MI_XALKY_IDLE_TIMEOUT_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'int',
		'default'     => '900'
);

$modversion['config'][] = array(
		'name'        => 'idleLogoutTimeout',
		'title'       => '_MI_XALKY_IDLE_LOGOUT_TIMEOUT',
		'description' => '_MI_XALKY_IDLE_LOGOUT_TIMEOUT_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'int',
		'default'     => '3600'
);

$modversion['config'][] = array(
		'name'        => 'adminArea',
		'title'       => '_MI_XALKY_ADMIN_AREA',
		'description' => '_MI_XALKY_ADMIN_AREA_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => '0'
);

$modversion['config'][] = array(
		'name'        => 'salt',
		'title'       => '_MI_XALKY_SALT',
		'description' => '_MI_XALKY_SALT_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'text',
		'default'     => (chr(mt_rand(ord("A"), ord("Z"))) . chr(mt_rand(ord("a"), ord("z"))) . chr(mt_rand(ord("`"), ord("/"))) . chr(mt_rand(ord("0"), ord("9"))) . chr(mt_rand(ord("a"), ord("Z"))) .  chr(mt_rand(ord("!"), ord("|"))) .chr(mt_rand(ord("A"), ord("Z"))) . chr(mt_rand(ord("a"), ord("z"))) . chr(mt_rand(ord("`"), ord("/"))) . chr(mt_rand(ord("0"), ord("9"))) . chr(mt_rand(ord("a"), ord("Z"))) .  chr(mt_rand(ord("!"), ord("|"))) . chr(mt_rand(ord("A"), ord("Z"))) . chr(mt_rand(ord("a"), ord("z"))) . chr(mt_rand(ord("`"), ord("/"))) . chr(mt_rand(ord("0"), ord("9"))) . chr(mt_rand(ord("a"), ord("Z"))) .  chr(mt_rand(ord("!"), ord("|"))) . chr(mt_rand(ord("A"), ord("Z"))) . chr(mt_rand(ord("a"), ord("z"))) . chr(mt_rand(ord("`"), ord("/"))) . chr(mt_rand(ord("0"), ord("9"))) . chr(mt_rand(ord("a"), ord("Z"))) .  chr(mt_rand(ord("!"), ord("|"))) . chr(mt_rand(ord("A"), ord("Z"))) . chr(mt_rand(ord("a"), ord("z"))) . chr(mt_rand(ord("`"), ord("/"))) . chr(mt_rand(ord("0"), ord("9"))) . chr(mt_rand(ord("a"), ord("Z"))) .  chr(mt_rand(ord("!"), ord("|"))) . chr(mt_rand(ord("A"), ord("Z"))) . chr(mt_rand(ord("a"), ord("z"))) . chr(mt_rand(ord("`"), ord("/"))) . chr(mt_rand(ord("0"), ord("9"))) . chr(mt_rand(ord("a"), ord("Z"))) .  chr(mt_rand(ord("!"), ord("|"))))   
);

$modversion['config'][] = array(
		'name'        => 'activeTimeout',
		'title'       => '_MI_XALKY_ACTIVE_TIMEOUT',
		'description' => '_MI_XALKY_ACTIVE_TIMEOUT_DESC',
		'formtype'    => 'text',
		'valuetype'   => 'int',
		'default'     => '60'
);

$modversion['config'][] = array(
		'name'        => 'showAdminResetPasswordLink',
		'title'       => '_MI_XALKY_ADMIN_RESET_PASSWORD_LINK',
		'description' => '_MI_XALKY_ADMIN_RESET_PASSWORD_LINK_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => '0'
);

$modversion['config'][] = array(
		'name'        => 'debug',
		'title'       => '_MI_XALKY_DEBUG',
		'description' => '_MI_XALKY_DEBUG_DESC',
		'formtype'    => 'yesno',
		'valuetype'   => 'int',
		'default'     => '0'
);

